FROM oven/bun:alpine

WORKDIR /app

# Copy dependency configs
COPY package.json ./

# Install development dependencies using Bun
RUN bun install

EXPOSE 3000

ENV PORT=3000
ENV NODE_ENV=development

CMD ["bun", "run", "dev"]
